src/DataVisualizer/Controllers/DataSourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataVisualizer.Models;
using DataVisualizer.Persistence;
using DataVisualizer.Persistence.Entity;

namespace DataVisualizer.Controllers
{
    public class DataSourceController : Controller
    {
        private readonly DataVisualizerContext dataVisualizerContext;
        public DataSourceController(DataVisualizerContext dataVisualizerContext)
        {
            if (dataVisualizerContext == null)
            {
                throw new ArgumentNullException(nameof(dataVisualizerContext));
            }

            this.dataVisualizerContext = dataVisualizerContext;
        }

        public IActionResult Index(DataSourceRegistrationRequest registrationRequest)
        {
            return View(registrationRequest);
        }

        [HttpPost]
        public IActionResult RegisterDataSource(DataSourceRegistrationRequest registrationRequest)
        {
            if(registrationRequest == null)
            {
                throw new ArgumentNullException(nameof(registrationRequest));
            }

            if(registrationRequest.Visualization == null)
            {
                throw new ArgumentNullException(nameof(registrationRequest.Visualization));
            }

            if(string.IsNullOrWhiteSpace(registrationRequest.Id))
            {
                throw new ArgumentNullException(nameof(registrationRequest.Id));
            }

            var idExists = dataVisualizerContext.DataSources.Any(_dataSource => _dataSource.Id == registrationRequest.Id);

            if(idExists)
            {
                ModelState.AddModelError(nameof(registrationRequest.Id), "A device with this Id already exists");
                return RedirectToAction("Index", new { registrationOptions = registrationRequest });
            }

            var dataSource = GetDataSource(registrationRequest);

            dataVisualizerContext.Add(dataSource);

            try
            {
                dataVisualizerContext.SaveChanges();
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "The data source could not be saved. An error occurred while saving the data source.");
                return RedirectToAction("Index", new { registrationOptions = registrationRequest });
            }

            return RedirectToAction("Index", new { registrationOptions = registrationRequest });
        }

        private DataSource GetDataSource(DataSourceRegistrationRequest registrationOptions)
        {
            var dataSource = new DataSource()
            {
                Id = registrationOptions.Id,
                Description = registrationOptions.Description,
                DataSourceVisualizations = new List<DataSourceVisualization>
                                 {
                                    new DataSourceVisualization()
                                    {
                                        Name = registrationOptions.Visualization.Name,
                                        Description = registrationOptions.Visualization.Description,
                                        Visualization = dataVisualizerContext.Visualizations.Single(visualization => visualization.Type == registrationOptions.Visualization.Type.ToString()),
                                        Properties = registrationOptions.Visualization.DataSourceToVisualizationPropertyMap
                                                        .Select( kvp => new DataSourceVisualizationProperty()
                                                                            {
                                                                                Key = kvp.Key,
                                                                                Value = kvp.Value
                                                                            }).ToList()
                                    }
                                 }
            };

            return dataSource;

        }

        [HttpGet]
        public IActionResult GetVisualizationProperties(VisualizationType visualizationType)
        {
            var properties = dataVisualizerContext.VisualizationProperties
                .Where(visualizationProperty => visualizationProperty.Visualization.Type == visualizationType.ToString())
                .Select(visualizationProperty => visualizationProperty.Value)
                .ToList();

            return new ObjectResult(properties);
        }


        [HttpPost]
        public async Task<IActionResult> SaveRecord([FromBody]SaveRecordRequest saveRecordRequest)
        {
            if (saveRecordRequest == null)
            {
                throw new ArgumentNullException(nameof(saveRecordRequest));
            }

            if(string.IsNullOrWhiteSpace(saveRecordRequest.DataSourceId))
            {
                throw new ArgumentNullException(nameof(saveRecordRequest.DataSourceId));
            }

            if (saveRecordRequest.Properties == null)
            {
                throw new ArgumentNullException(nameof(saveRecordRequest.Properties));
            }

            try
            {
                //Reversing key an value on purpose. Need to do a reverse lookup.
                var dataSourceVisualizationProperties = dataVisualizerContext.DataSourceVisualizationProperties
                    .Where(property => property.DataSourceVisualization.Id == saveRecordRequest.DataSourceVisualizationId)
                    .ToDictionary(property => property.Value, 
                                  property => property.Key);

                var record = new Record()
                {
                    DataSource = dataVisualizerContext.DataSources
                                    .Single(dataSource => dataSource.Id == saveRecordRequest.DataSourceId),

                    DataSourceVisualization = dataVisualizerContext.DataSourceVisualizations
                                                .Single(dsv => dsv.Id == saveRecordRequest.DataSourceVisualizationId),

                    Properties = saveRecordRequest.Properties.Select(kvp => new RecordProperty()
                    {
                        Key = dataSourceVisualizationProperties[kvp.Key],
                        Value = kvp.Value
                    }).ToList()
                };


                dataVisualizerContext.Records.Add(record);
            }
            catch(KeyNotFoundException ex)
            {
                //TODO: Informative error.
                return new ObjectResult(false);
            }
            catch(Exception ex)
            {
                //TODO: Logging, better user error
                return new ObjectResult(false);
            }

            try
            {
                await dataVisualizerContext.SaveChangesAsync();
            }
            catch(Exception ex)
            {
                //TODO: Logging, better user error
                return new ObjectResult(false);
            }

            return new ObjectResult(true);
        }

    }
}

src/DataVisualizer/Views/DataSource/Index.cshtml
@using DataVisualizer.Models
@model DataSourceRegistrationRequest

<form asp-controller="DataSource" asp-action="RegisterDataSource" method="post" class="form-horizontal">
    <h4>Register a New Data Source</h4>

    <div asp-validation-summary="@ValidationSummary.All" class="text-danger"></div>

    <h4>Data Source</h4>

    <hr/>

    <div class="form-group">
        <label asp-for="Id" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Id" class="form-control" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Description" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>

    <h4>Visualization</h4>

    <hr/>

    <div class="form-group">
        <label asp-for="Visualization.Type" class="col-md-2 control-label">Type</label>

        <div class="col-md-10">
            <select id="visualization-type" asp-for="Visualization.Type" class="form-control" asp-items="@(Html.GetEnumSelectList<VisualizationType>())">
            </select>

            <span asp-validation-for="Visualization.Type" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Visualization.Name" class="col-md-2 control-label">Name</label>
        <div class="col-md-10">
            <input asp-for="Visualization.Name" class="form-control"/>
            <span asp-validation-for="Visualization.Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Visualization.Description" class="col-md-2 control-label">Name</label>
        <div class="col-md-10">
            <input asp-for="Visualization.Description" class="form-control" />
            <span asp-validation-for="Visualization.Description" class="text-danger"></span>
        </div>
    </div>

    <div id="visualization-custom-properties">

    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>

    
</form>

@section scripts {

}

<script type="text/javascript">
    const visualizationTypeSelect = document.querySelector('#visualization-type');
    const visualizationPropertiesContainer = document.querySelector('#visualization-custom-properties');
    const endpoint = '@Url.Action("GetVisualizationProperties", "DataSource")';

    function renderVisualizationProperties(properties) {
        const html = properties.map((property, index) => {
            return `
                <div class="form-group">
                    <label for="Visualization.DataSourceToVisualizationPropertyMap[${property}]" class ="col-md-2 control-label">${property}</label>
                    <div class="col-md-10">
                        <input id="Visualization.DataSourceToVisualizationPropertyMap[${property}]" name="Visualization.DataSourceToVisualizationPropertyMap[${property}]" class ="form-control" />
                    </div>
                </div>
                `;
        
        }).join('');

        visualizationPropertiesContainer.innerHTML = html;
    }

    function getVisualizationProperties(e) {
        const properties = [];
        fetch(endpoint)
            .then(blob => blob.json())
            .then(data => properties.push(...data))
            .then(data => renderVisualizationProperties(properties));
    }

    visualizationTypeSelect.addEventListener('change', getVisualizationProperties);

    getVisualizationProperties();
</script>